# application.yml

server:
  port: 8080

spring:
  application:
    name: bank-card-management

  # PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_cards
    username: bankcards
    password: bankcards
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Liquibase
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  # Jackson
  jackson:
    datatype:
      datetime:
        write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# Spring Security + JWT настройки
security:
  jwt:
    secret: 451af376a99fea3a776c8d3d0b7cfe75e1df0741ab2718ee685e9d1452608d13987f49bdba3fff245bb71be0254886cf26626b24957d8640a62ec016b847293d #${JWT_SECRET}
    expiration: 86400000          # 24 часа
    refresh-token-expiration: 604800000   # 7 дней

# Swagger / OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
  paths-to-match:
    - /api/**
  packages-to-scan:
    - com.example.bankcards.controller

# Logging
logging:
  level:
    root: ERROR
    org.springframework: ERROR
    org.springframework.security: DEBUG
    org.hibernate: ERROR
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.example.bankcards: DEBUG

# Профили (dev / test)
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/bank_cards_dev
    username: postgres
    password: postgres

  jpa:
    show-sql: true

logging:
  level:
    com.example.bankcards: DEBUG
    org.springframework.security: DEBUG

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:tc:postgresql:16:///testdb?TC_IMAGE_TAG=16
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  jpa:
    show-sql: false